### ISSUE TITLE
Yarn error showing when trying to run example project with no changes but not using yarn

### ISSUE THREAD

**Issue by imtiazhossain** [burakkaygusuz/cypress-cucumber-test-example#205]
✘ [ERROR] Could not resolve "@badeball/cypress-cucumber-preprocessor"

    cypress/e2e/step_definitions/signIn_spec.js:1:34:
      1 │ ...Given, Then, When } from '@badeball/cypress-cucumber-preprocessor';
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@badeball/cypress-cucumber-preprocessor" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@badeball/cypress-cucumber-preprocessor" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@faker-js/faker"

    cypress/e2e/step_definitions/signIn_spec.js:2:22:
      2 │ import { faker } from '@faker-js/faker';
        ╵                       ~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@faker-js/faker" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@faker-js/faker" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@cucumber/cucumber-expressions"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/registry.js:7:39:
      7 │ ...cucumber_expressions_1 = require("@cucumber/cucumber-expressions");
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@cucumber/cucumber-expressions" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@cucumber/cucumber-expressions" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@cucumber/tag-expressions"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/registry.js:8:50:
      8 │ ...ressions_1 = __importDefault(require("@cucumber/tag-expressions"));
        ╵                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@cucumber/tag-expressions" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@cucumber/tag-expressions" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@cucumber/messages"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:30:38:
      30 │ const messages = __importStar(require("@cucumber/messages"));
         ╵                                       ~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@cucumber/messages" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@cucumber/messages" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "error-stack-parser"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/source-map.js:7:53:
      7 │ ...or_stack_parser_1 = __importDefault(require("error-stack-parser"));
        ╵                                                ~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "error-stack-parser" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "error-stack-parser" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@cucumber/tag-expressions"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:31:50:
      31 │ ...essions_1 = __importDefault(require("@cucumber/tag-expressions"));
         ╵                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@cucumber/tag-expressions" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@cucumber/tag-expressions" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@cucumber/cucumber-expressions"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:32:39:
      32 │ ...ucumber_expressions_1 = require("@cucumber/cucumber-expressions");
         ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@cucumber/cucumber-expressions" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@cucumber/cucumber-expressions" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "uuid"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:33:23:
      33 │ const uuid_1 = require("uuid");
         ╵                        ~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "uuid" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "uuid" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "seedrandom"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:34:45:
      34 │ const seedrandom_1 = __importDefault(require("seedrandom"));
         ╵                                              ~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "seedrandom" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "seedrandom" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

✘ [ERROR] Could not resolve "@cucumber/messages"

    node_modules/@badeball/cypress-cucumber-preprocessor/dist/helpers/snippets.js:27:38:
      27 │ const messages = __importStar(require("@cucumber/messages"));
         ╵                                       ~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@cucumber/messages" here because it's not listed as a dependency of this package:

    ../.pnp.js:47:33:
      47 │           "packageDependencies": [
         ╵                                  ^

  You can mark the path "@cucumber/messages" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

Oops...we found an error preparing this test file:

  > cypress/e2e/signIn.feature

The error was:

Error: Build failed with 11 errors:
cypress/e2e/step_definitions/signIn_spec.js:1:34: ERROR: Could not resolve "@badeball/cypress-cucumber-preprocessor"
cypress/e2e/step_definitions/signIn_spec.js:2:22: ERROR: Could not resolve "@faker-js/faker"
node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:30:38: ERROR: Could not resolve "@cucumber/messages"
node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:31:50: ERROR: Could not resolve "@cucumber/tag-expressions"
node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:32:39: ERROR: Could not resolve "@cucumber/cucumber-expressions"
...
    at failureErrorWithLog (/Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/ihossain/repos/cypress-cucumber-test-example/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

**Comment by imtiazhossain** [comment]
Sorry this issue is on my end
